services:
  app:
    build: ./speedtest
    networks:
      - app-net
    ports:
      - "9000:9000"
    environment:
      - TITLE=LibreSpeed
      - MODE=frontend
      - PASSWORD=pas123
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - REDACT_IP_ADDRESSES=false
      - DB_TYPE=mysql
    volumes:
      - ./speedtest/docker/servers.json:/servers.json
      - ./caddy_data:/var/www/html
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  db:
    image: mysql/mysql-server:8.0 
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-net  
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: stuser123
      MYSQL_USER: stuser
      MYSQL_PASSWORD: stuser123
      MYSQL_DATABASE: speedtest
    volumes:
      - ./speedtest/results:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  caddy:
    image: caddy:2.4.3
    restart: unless-stopped
    networks:
      - app-net    
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/var/www/html
    depends_on:
      - app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

volumes:
  db_data:
    external: true

networks: 
  app-net: 
    external: 
      name: app-net
