version: "3"
services:
  fluentd:
    build: ./fluentd
    networks:
      - app-net  
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 10m
            max-file: "5"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    networks:
      - app-net   
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224


  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    networks:
      - app-net    
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "5601:5601"
    depends_on:
      - fluentd
      - elasticsearch
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

networks: 
  app-net: 
    external: 
      name: app-net 


